@startuml
!startsub DataModelError
namespace score::config_management::config_daemon::data_model {
enum DataModelError {
    kParameterMissedError
    kConvertingError
    kParsingError
    kParameterSetNotFound
    kParametersNotFound
    kParentParameterDataNotfound
    kParameterSetNotCalibratable
    kParameterAlreadyExists
}
}
!endsub

@enduml
