@startuml

skinparam SequenceMessageAlignment center
title ConfigDaemon Provided Services

participant "mw::com" as mwcom
participant InternalConfigProviderService
participant InternalConfigProviderServiceReactor
participant ParameterSetCollection

activate mwcom
-> mwcom : GetParameterSet(parameter_set_name)
activate InternalConfigProviderService
mwcom -> InternalConfigProviderService : GetParameterSet(parameter_set_name)
activate InternalConfigProviderServiceReactor
InternalConfigProviderService -> InternalConfigProviderServiceReactor : GetParameterSet(parameter_set_name)
activate ParameterSetCollection
InternalConfigProviderServiceReactor -> ParameterSetCollection : GetParameterSet(parameter_set_name)
InternalConfigProviderServiceReactor <-- ParameterSetCollection : parameter_set
deactivate ParameterSetCollection
InternalConfigProviderService <-- InternalConfigProviderServiceReactor : parameter_set
deactivate InternalConfigProviderServiceReactor
mwcom <-- InternalConfigProviderService : parameter_set
deactivate InternalConfigProviderService
<-- mwcom
deactivate mwcom

@enduml
