@startuml

!startsub ConfigProviderLibrary

!includesub score/config_management/config_daemon/detailed_design/assets/external_libs.puml!Logger
!includesub score/config_management/config_daemon/detailed_design/assets/external_libs.puml!MemoryResource
!includesub score/config_management/config_daemon/detailed_design/assets/plugins/coding/external_libs.puml!ProxyNeedsFactory
!includesub score/config_management/config_daemon/detailed_design/assets/plugins/coding/external_libs.puml!ProxyNeeds
!includesub score/config_management/config_daemon/detailed_design/assets/plugins/coding/external_libs.puml!AdaptiveImmediateInstantiationStrategy
!includesub score/config_management/ConfigProvider/detailed_design/assets/config_provider/factory/config_provider_factory.puml!ConfigProviderFactory
!includesub score/config_management/config_daemon/detailed_design/assets/data_model/parameterset_collection/parameterset_collection.puml!ParameterSet
!includesub score/config_management/config_daemon/detailed_design/assets/data_model/parameterset_collection/parameterset_collection.puml!ParameterSetQualifier
!includesub score/config_management/ConfigProvider/detailed_design/assets/config_provider/error/error.puml!ConfigProviderError
!includesub score/config_management/ConfigProvider/detailed_design/assets/config_provider/initial_qualifier_state_types.puml!InitialQualifierState

package "ConfigProvider" <<frame>> {
    !includesub score/config_management/ConfigProvider/detailed_design/assets/config_provider/config_provider.puml!ConfigProvider
    !includesub score/config_management/ConfigProvider/detailed_design/assets/config_provider/config_provider.puml!ConfigProviderImpl
}

package "Persistency" <<frame>> {
    !includesub score/config_management/ConfigProvider/detailed_design/assets/persistency/factory/persistency_factory.puml!PersistencyFactory
    !includesub score/config_management/ConfigProvider/detailed_design/assets/persistency/persistency.puml!Persistency
    !includesub score/config_management/ConfigProvider/detailed_design/assets/persistency/persistency.puml!PersistencyImpl
    !includesub score/config_management/ConfigProvider/detailed_design/assets/persistency/persistency.puml!PersistencyImpl
    !includesub score/config_management/ConfigProvider/detailed_design/assets/persistency/error/error.puml!PersistencyError
}

package "InternalConfigProvider_proxy" <<frame>> {
    !includesub score/config_management/ConfigProvider/detailed_design/assets/proxies/internal_config_provider.puml!IInternalConfigProvider
    !includesub score/config_management/ConfigProvider/detailed_design/assets/proxies/internal_config_provider.puml!InternalConfigProvider
}

 /' Packages relationships '/

package "Persistency" <<Persistency>> {
    Persistency <|-right- PersistencyImpl
    Persistency <|-right- PersistencyImpl
    PersistencyImpl <-down- PersistencyFactory : construct
    PersistencyImpl <-down- PersistencyFactory : construct
    PersistencyImpl ..> PersistencyError : report
    class KeyValueStorage <<external>> #LightGray {
        Responsibility: External mw::per key/value storage API used by PersistencyImpl
    }
    PersistencyImpl *-- KeyValueStorage : uses
}

package "InternalConfigProvider_proxy" <<InternalConfigProvider_proxy>> {
    class Proxies{
    using Proxies = mw::service::ProxyNeeds<IInternalConfigProvider>
    --
    Responsibility: Owns a single instance of InternalConfigProvider proxy.
    }

    class InternalConfigProviderProxy <<generated>> #Gray{
        Responsibility: This is the generated proxy from mw::com.
    }
    InternalConfigProvider *-- InternalConfigProviderProxy
    Proxies o-- IInternalConfigProvider
}

Adaptive_Application *-- ConfigProvider.ConfigProvider
Adaptive_Application -left-> PersistencyFactory : construct
Adaptive_Application --> ConfigProviderFactory : construct
ConfigProviderImpl <-right- ConfigProviderFactory : construct
Persistency.Persistency --* ConfigProviderImpl
ParameterSet <-up- ConfigProviderImpl : creates & returns
ConfigProviderImpl ..> ConfigProviderError : create
ConfigProviderImpl *-- IInternalConfigProvider
ConfigProviderFactory -down-> Proxies : construct
ConfigProviderFactory -up-> ProxyNeedsFactory : use Strategy: InternalConfigProviderStrategy ProxyNeeds: mw::service::Optional<IInternalConfigProvider>
ConfigProviderFactory --> ProxyNeeds
ConfigProviderFactory --> AdaptiveImmediateInstantiationStrategy
ConfigProviderFactory --> score::cpp::pmr::memory_resource : Use
ParameterSet o-- ParameterSetQualifier
ParameterSet ..> ConfigProviderError
InitialQualifierState ..> PersistencyError
ConfigProvider.ConfigProvider .up.> Logger : Use

note right of ParameterSet #LightSkyBlue
    ConfigProviderImpl creates a ParameterSet as a business
    object abstraction for a specific user application.

    We use a shared_ptr, since the OnChange callback
    will need to capture the ParameterSet map.
end note

note left of InternalConfigProviderProxy #LightSkyBlue
    Following the Proxy-Pattern of mw::service
end note

@enduml
