@startuml

!startsub ConfigProviderError
enum ConfigProviderError {
    kParsingFailed
    kObjectCastingError
    kParameterNotFound
    kValueCastingError
    kValueNotFound
    kProxyNotReady
    kProxyAccessTimeout
    kProxyReturnedNoResult
    kEmptyCallbackProvided
    kCallbackAlreadySet
    kMethodNotSupported
    kFailedToSubscribe
    kParameterSetNotFound
}
!endsub

@enduml
