@startuml

!startsub IParamSetMapping
abstract class IParamSetMapping{
    + {abstract} GetNamesOfParametersInSet(param_set_name : const score::cpp::pmr::string&) :
                const score::Result<score::cpp::pmr::vector<score::cpp::string_view>>
    + {abstract} GetParameterSetForParameter(
            parameter_name : const score::cpp::pmr::string&) : const score::cpp::string_view
    + {abstract} LoadParameterSetConfig(): ResultBlank
    --
    # IParamSetMapping(IParamSetMapping&&)
    # operator=(IParamSetMapping&&) : IParamSetMapping&
    --
    Responsibility: This class manages the mapping between ParameterSet name
    and Parameter name based on a configuration file.
}
!endsub

!startsub ParamSetMapping
class ParamSetMapping{
    + ParamSetMapping(json_parser : const std::shared_ptr<json::IJsonParser>)
    + GetNamesOfParametersInSet(param_set_name : const score::cpp::pmr::string&) :
                const score::Result<score::cpp::pmr::vector<score::cpp::string_view>>
    + GetParameterSetForParameter(
            parameter_name : const score::cpp::pmr::string&) : const score::cpp::string_view
    + LoadParameterSetConfig(): ResultBlank
    + operator=(ParamSetMapping&&) : ParamSetMapping&
    + ParamSetMapping(ParamSetMapping&&)
    --
    - logger_ : mw::log::Logger
    - param_set_to_params_mapping_ : score::cpp::pmr::unordered_map<score::cpp::pmr::string, score::cpp::pmr::vector<score::cpp::pmr::string>>
    - param_to_param_sets_mapping_ : score::cpp::pmr::unordered_map<score::cpp::pmr::string, score::cpp::pmr::string>
    - json_parser_ : std::shared_ptr<json::IJsonParser>
}
IParamSetMapping <|-down- ParamSetMapping
!endsub


@enduml
